create initial boilerplate app
acmucsd/green-team-backend pull request #1
Opened 2020-04-09 03:25 UTC by shravanhariharan2

Initial boilerplate application with controllers, models, and db setup. Would appreciate architecture tips and advice for potential better structure/workflow. Build instructions and app architecture are described in the README

2020-04-09 05:02 UTC, sumeet-bansal requested changes
Nice boilerplate! The app itself doesn't need to go into a Docker container since `pip` like `npm` ensures the same dependencies install each time.

2020-04-09 05:02 UTC, sumeet-bansal commented on README.md
> +DB_HOST=db      // name of docker container database service, which is "db" in docker-compose.yml
Does this work on Windows? I've had trouble in the past on Windows accessing containers by their given name.

2020-04-09 05:02 UTC, sumeet-bansal commented on README.md
> +* `/app/models` - contains database models (schemas) and classes to create objects
I think `models` should go in the `database` folder.

2020-04-09 05:02 UTC, sumeet-bansal commented on manage.py
> +# Create development app (can change to "prod" for production)
If you want to change it to "production" you'll need to have it be configurable.

2020-04-09 05:02 UTC, sumeet-bansal commented on app/models/nodeModel.py
> +    id = db.Column(db.Integer, primary_key=True)
You can still use auto-incrementing IDs as a primary key but consider using UUIDs to actually identify nodes (although you can certainly get away with only simple integer IDs here since the database isn't going to be distributed).

2020-04-09 05:02 UTC, sumeet-bansal commented on app/models/nodeModel.py
> +    value = db.Column(db.String(128))
What does "value" represent? A person's name? A tree's/family's name?

2020-04-09 05:02 UTC, sumeet-bansal commented on app/models/nodeModel.py
> +    children = db.Column(postgresql.ARRAY(db.Integer))
If you use a Postgres-specific data type here, you'll tie the app to Postgres for the database. One of the hallmarks of good architecture is decoupling, i.e. how easy it is to replace something, like switching to another database.

An array definitely makes sense for the job and simplifies your database schema, but adding another table to keep track of connections (bit-byte relationships) decouples the schema from Postgres-specific features. And IMO, arrays don't really belong in SQL anyways.

This app is probably going to use Postgres forever and the database layer is still abstracted away, so it's not that difficult to switch to like Mongo or something, but something to consider.

2020-04-09 05:02 UTC, sumeet-bansal commented on README.md
> +* Data in the database does not persist after closing containers
Does "closing" mean "stopping" in this case? The data should absolutely persist if you stop a container but gets erased if you delete the container.

2020-04-09 05:02 UTC, sumeet-bansal commented on app/config.py
> +# Any way to make this url cleaner?
> Any way to make this url cleaner?

Put the URI itself as the environment variable or use a template string.

2020-04-09 05:02 UTC, sumeet-bansal commented on app/models/__init__.py
> +__all__ = ["Node", "db"]
A little strange to export the `db` instance since that allows other modules/layers to break the database abstraction and directly do database operations instead of going through predefined model functions.

Move `models` under `database` and export the model in `database/__init__.py`.

2020-04-09 05:02 UTC, sumeet-bansal commented on app/models/nodeModel.py
> +class Node(db.Model):
We're using a node structure but "Node" as a class name doesn't tell you anything about what this data structure actually represents.

2020-04-09 05:02 UTC, sumeet-bansal commented on app/config.py
> +key = Config.SECRET_KEY
What's this do?

2020-04-09 05:02 UTC, sumeet-bansal commented on app/api/nodeRouter.py
> +        return "Error: No request body provided"
Use a [guard clause](https://www.carloscaballero.io/refactoring-guard-clauses/) here.

2020-04-09 05:02 UTC, sumeet-bansal commented on app/api/nodeRouter.py
> +@node_blueprint.route("/", methods=["POST"])
Nit: put all the same routes together (group this with the GET on the same route).

2020-04-09 05:02 UTC, sumeet-bansal commented on app/api/__init__.py
> +node_blueprint = Blueprint('node_blueprint', __name__, url_prefix="/nodes")
I find it a little strange to declare the router here and then add functions to it in its own file instead of declaring the route in its own file with its functions and then importing it here. Not sure if you can do that since `url_prefix` is a constructor parameter though?

2020-04-11 05:35 UTC, shravanhariharan2 commented on README.md
> +* Data in the database does not persist after closing containers
Sorry for the confusion - losing means deleting the containers here. Stopping the containers and restarting them does persist the data

2020-04-11 05:51 UTC, sumeet-bansal commented on README.md
> +* Data in the database does not persist after closing containers
Can you update the note to make that clear? Although honestly I think it goes without saying that data doesn't persist if you delete the database.

Also, I didn't pick this up before but `pip freeze` lists all dependencies, including dependencies of dependencies and dependencies of dependencies of dependencies, etc. so it might just be better to manually add dependencies to the `requirements.txt` (unfortunately I don't think there's a pip equivalent to npm's `--save` flag).

2020-04-11 19:25 UTC, shravanhariharan2 commented on README.md
> +DB_HOST=db      // name of docker container database service, which is "db" in docker-compose.yml
Just tried on a Windows machine and it seems to work fine for me (Windows 10 Home with Docker Desktop). I'm not 100% sure how Docker networking actually works and this is kind of a shot in the dark, but I think the reason may be because the Flask API container is the one accessing the database container and not the Windows machine? No clue if this is at all correct and just based off of a response to a thread I read [here](https://forums.docker.com/t/cant-connect-to-container-on-localhost-mapped-port/31887/2).

Also, regarding the app not needing to go into a container, I was just curious what were the advantages/disadvantages of having it non-containerized vs. containerized? My intuition was that if I could type one command to spin up everything I needed and just have the containers talk to each other then that would make things a lot easier, but I'm thinking there's probably some overhead that I wasn't initially aware of.

2020-04-11 19:38 UTC, shravanhariharan2 commented on README.md
> +* Data in the database does not persist after closing containers
So for `pip freeze`, wouldn't the dependencies of dependencies of dependencies etc. need to exist so that the root dependencies work? Or do the root dependencies work just as usual by themselves?

2020-04-11 21:32 UTC, sumeet-bansal commented on README.md
> +* Data in the database does not persist after closing containers
Yes but if you just have the root dependencies, `pip install` will install anything nested, so you can keep the `requirements.txt` more organized by only including the app's direct dependencies. The tradeoff is that you're not tracking the nested dependencies (like `package-lock.json` does), but that's usually not an issue.

2020-04-11 21:42 UTC, sumeet-bansal approved these changes
Some comments about the `BitByteNode` model but looks good!

2020-04-11 21:42 UTC, sumeet-bansal commented on app/services/nodeService.py
> +        node["child_node_2"])
It's really easy to pass in parameters in the wrong order with this many and you're listing all the attributes twice (here and in the `BitByteNode` constructor) so it'd be cleaner to just pass in the entire `node` object into the constructor.

2020-04-11 21:42 UTC, sumeet-bansal commented on app/database/models/nodeModel.py
> +        self.child_node_2 = child_node_2
If someone's a byte for multiple years, can they pick up 2+ bits? Or like, if a byte has 2 bits and one drops out and the byte picks up another bit, how's that work? I still think a separate `Connections` table is more extendable and probably makes advanced SQL queries a bit easier (e.g. getting an entire lineage via recursive query) but that might be overengineering a little so your call&mdash;just my opinion.

2020-04-12 02:07 UTC, leestanley commented on app/database/models/nodeModel.py
> +        self.child_node_2 = child_node_2
I'm highly confident some bytes will pick up 2 bits in the future, there also edge cases for the front end like displaying 5+ bits on a node as well @YiyueMaggieMao & @michelemurakami

2020-04-12 02:11 UTC, leestanley approved these changes

2020-04-12 02:19 UTC, shravanhariharan2 commented on app/database/models/nodeModel.py
> +        self.child_node_2 = child_node_2
Yeah you're right, bytes can have different bits each year so they can ultimately have more than 2 bits. I was a little confused how to create a `Connections` table initially, like I'm thinking about having 2 fields, one being a `parent_node_id` that's a foreign key to the parent node's id and the other being a `node_id` with a foreign key mapping to the current node id. Not sure if that works having foreign keys that map to the same field of a table but I'll try it out.

2020-04-12 03:20 UTC, shravanhariharan2 commented
So I created a `Connections` model that supports inner join queries to get all children nodes for a parent, but there's still a lot of functionality needed to be built regarding creating, establishing, and getting connections (like figuring out who the byte is, since down the line someone can be both a bit and a byte) that I think is beyond the scope of a boilerplate pull request so I'm going to close this PR and we can flesh out connections in the future

2020-04-12 03:22 UTC, merged