implement glossary functionality
acmucsd/green-team-backend pull request #7
Opened 2020-05-21 05:36 UTC by shravanhariharan2

2020-05-25 06:22 UTC, trulyronak approved these changes
could improve on adding status codes for errors, give more info when you fail

status codes could reflect what failed

functionality lgtm

2020-05-27 20:47 UTC, sumeet-bansal approved these changes

2020-05-27 20:47 UTC, sumeet-bansal commented on app/api/treeRouter.py
> +        tree = treeService.addPointsById(body["id"], body["points"])
Check for `body['id']` and `body['points']`.

2020-05-27 20:47 UTC, sumeet-bansal commented on app/config.py
> +    MAX_CONTENT_LENGTH = 512 * 1024
Specify units: `MAX_CONTENT_SIZE_IN_BYTES`.

2020-05-27 23:24 UTC, shravanhariharan2 commented on app/config.py
> +    MAX_CONTENT_LENGTH = 512 * 1024
`MAX_CONTENT_LENGTH` is a field that `werkzeug` expects in the app config for the `RequestEntityTooLarge` exception to be properly thrown, so I just added a conversion constant to make the conversion clearer

2020-05-27 23:34 UTC, sumeet-bansal requested changes

2020-05-27 23:34 UTC, sumeet-bansal commented on app/api/treeRouter.py
> +        if not body or body["id"] or body["points"]:
I'd expect the `not` to only apply to `body` so you'd end up returning an error if `body['id']` or `body['points']` is present.
[
<img width="266" alt="Screen Shot 2020-05-27 at 4 33 52 PM" src="https://user-images.githubusercontent.com/29763383/83082308-edb61500-a037-11ea-9c22-b0a10fdd1e17.png">
](url)

2020-05-28 00:19 UTC, shravanhariharan2 commented on app/api/treeRouter.py
> +        if not body or body["id"] or body["points"]:
whoops thanks, turns out I was also getting a `KeyError` for accessing "id" or "points" if it wasn't passed in too so fixed that as well.

2020-05-31 00:18 UTC, sumeet-bansal approved these changes

2020-05-31 00:20 UTC, merged